/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.themultiverseoffreddys;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class UltimateFnafModModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();

	public UltimateFnafModModElements() {
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "deadeyes"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "deadeyes")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "chica1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "chica1")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "bonnie1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "bonnie1")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "death1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "death1")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "deathgolden1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "deathgolden1")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "foxy1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "foxy1")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "freddy1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "freddy1")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "golden1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "golden1")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "walk1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "walk1")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "walkfoxy1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "walkfoxy1")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "walkgolden1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "walkgolden1")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "bb2"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "bb2")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "death2"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "death2")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "mangle2"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "mangle2")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "puppet2"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "puppet2")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "walk2"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "walk2")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "death3"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "death3")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "mangle3"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "mangle3")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "puppet3"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "puppet3")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "shadow3"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "shadow3")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "deathshadow3"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "deathshadow3")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "bb4"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "bb4")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "death4"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "death4")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "dreadbear4"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "dreadbear4")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "foxy4"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "foxy4")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "fredbear4"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "fredbear4")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "mangle4"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "mangle4")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "deathshort4"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "deathshort4")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "deathnightmare4"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "deathnightmare4")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "walk4"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "walk4")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "walk3"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "walk3")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "freddy5"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "freddy5")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "lolbit5"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "lolbit5")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "deathshort5"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "deathshort5")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "walk5"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "walk5")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "death6"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "death6")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "helpy6"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "helpy6")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "deathhelpy6"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "deathhelpy6")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "lefty6"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "lefty6")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "walk6"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "walk6")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "death7"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "death7")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "fredbear7"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "fredbear7")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "summon7"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "summon7")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "xor7"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "xor7")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "deathglitchtrap8"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "deathglitchtrap8")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "deathplush8"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "deathplush8")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "death9"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "death9")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "death_f"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "death_f")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "death_c"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "death_c")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "death_ar"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "death_ar")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "death_j"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "death_j")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "death_p"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "death_p")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "death_ti"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "death_ti")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "deathhourglass_ti"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "deathhourglass_ti")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "forgottenone_ti"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "forgottenone_ti")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "mickey_ti"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "mickey_ti")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "death_tjoc"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "death_tjoc")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "puppet4"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "puppet4")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "death5"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "death5")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "walk_big"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "walk_big")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "molten6"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "molten6")));
		sounds.put(new ResourceLocation("ultimate_fnaf_mod", "hurt1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("ultimate_fnaf_mod", "hurt1")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("ultimate_fnaf_mod").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == UltimateFnafModModElements.ModElement.class)
						elements.add((UltimateFnafModModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(UltimateFnafModModElements.ModElement::initElements);
		MinecraftForge.EVENT_BUS.register(new UltimateFnafModModVariables(this));
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	private int messageID = 0;

	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		UltimateFnafModMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}

	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}

		protected final UltimateFnafModModElements elements;
		protected final int sortid;

		public ModElement(UltimateFnafModModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
